### ISSUE TITLE
Partial matches not found

### ISSUE THREAD

**Issue by ojalaquellueva** [ojalaquellueva/TNRSbatch#4]
Partial match to genus not found if full species name does not match. Originally reported as issue #6 "Sometimes fail to detect valid Genus due to wrong epithet" in RTNRS repository (https://github.com/EnquistLab/RTNRS/issues/6).

**Comment by ojalaquellueva** [comment]
Testing for single-threaded batch application: 

WD="/home/bien/tnrs/admin/bugs/partial_match"
APPD="/home/bien/tnrs/tnrs_batch/src"

cat << EOT > partial_match_bug_test.csv
Connarus venezuelanus
Connarus venezuelensis
Croton antisyphiliticus
Croton antisiphyllitius
Connarus sp.1
Connarus
Connaraceae Connarus absurdus
Connarus absurdus
Connaraceae Badgenus badspecies
Rosaceae Badgenus badspecies
EOT

php ${APPD}/taxamatch_superbatch.php -s "tropicos,wfo,usda" -f "${WD}/partial_match_bug_test.csv" -o "${WD}/partial_match_bug_test_scrubbed.tsv" -m

awk -F '\t' '{print $2 "\t" $5}' partial_match_bug_test_scrubbed.tsv | tr -d '\"' | tr -d "'" | column -t -s $'\t'
Name_submitted                   Name_matched
Connarus venezuelanus            Connarus venezuelanus
Connarus venezuelensis           Connarus
Croton antisyphiliticus          Croton antisyphiliticus
Croton antisiphyllitius          Croton
Connarus sp.1                    Connarus
Connarus                         Connarus
Connaraceae Connarus absurdus    Connarus
Connarus absurdus                Connarus
Connaraceae Badgenus badspecies  Connaraceae
Rosaceae Badgenus badspecies     Rosaceae
```
***Issue not replicated***

**Comment by ojalaquellueva** [comment]
### Testing for parallel application


```
php ${APPD}/taxamatch_superbatch.php -s "tropicos,wfo,usda" -f "${WD}/partial_match_bug_test.csv" -o "${WD}/partial_match_bug_test_scrubbed.tsv" -m


sudo ${APPD}/controller.pl -in "${WD}/partial_match_bug_test.csv"  -out "${WD}/partial_match_bug_test_scrubbed.par.tsv" -sources "tropicos,wfo,usda" -class tropicos -nbatch 4 -d t 

awk -F '\t' '{print $2 "\t" $5}' partial_match_bug_test_scrubbed.par.tsv | tr -d '\"' | tr -d "'" | column -t -s $'\t'
Name_submitted                   Name_matched
Connarus venezuelanus            Connarus venezuelanus
Connarus venezuelensis           Connarus
Croton antisyphiliticus          Croton antisyphiliticus
Croton antisiphyllitius          Croton
Connarus sp.1                    Connarus
Connarus                         Connarus
Connaraceae Connarus absurdus    Connarus
Connarus absurdus                Connarus
Connaraceae Badgenus badspecies  Connaraceae
Rosaceae Badgenus badspecies     Rosaceae
```
***Issue not replicated***

**Comment by ojalaquellueva** [comment]
Cannot replicate issue with core services. Closing issue for this application.

**Comment by paternogbc** [comment]
Thanks for following up. Just to add, I also tested in the online (https://tnrs.biendata.org/) and the problem is exactly the same. 
![image](https://user-images.githubusercontent.com/9639481/155272220-8b70a20a-51c7-4f91-a147-40ddf5d91712.png)

**Comment by ojalaquellueva** [comment]
Thanks @paternogbc. As you can see from the above tests, the issue isn't with the TNRS but with the API, which its own repo. I've opened a new issue report here: https://github.com/ojalaquellueva/TNRSapi/issues/7
