### ISSUE TITLE
Unmatched epithets causing failure to return matched genus

### ISSUE THREAD

**Issue by tyeentaylor** [ojalaquellueva/TNRSbatch#6]
I'm using the online [tnrs.biendata.org](http://tnrs.biendata.org/) app. Try running these two names:

Helianthostylis sprucei
Helianthostylis tomentosa

The genus is spelled exactly the same. But the H. tomentosa result is "no match found", and does not return the genus match. It used to return the genus match without a species match, and then I could add back in the original epithet.

**Comment by ojalaquellueva** [comment]
I can replicate this on the TNRS web app, but not with the api. Calling from the shell with script "tnrs_api_example.sh" (see https://github.com/ojalaquellueva/TNRSapi/blob/master/tnrs_api_example.sh), the response is as expected:

Input file (test_names.csv):

```
ID,Name_submitted
1,Helianthostylis sprucei
2,Helianthostylis tomentosa
```

Command:

```
./tnrs_api.sh -m resolve -s wfo,wcvp -c wfo -f /home/bien/tnrs/admin/bugs/tnrs_batch_issue_6/test_names.csv
```

Response:

```
Names submitted:
| ID | Name_submitted            |
| -- | ------------------------- |
|  1 | Helianthostylis sprucei   |
|  2 | Helianthostylis tomentosa |
 
Processing with TNRS API @ 'https://tnrsapi.xyz/tnrs_api.php'
 
Name resolution results:
| Name_submitted            | Name_matched            | Overall_score | Taxonomic_status | Accepted_name           |
| ------------------------- | ----------------------- | ------------- | ---------------- | ----------------------- |
| Helianthostylis sprucei   | Helianthostylis sprucei |           1.0 | Accepted         | Helianthostylis sprucei |
| Helianthostylis tomentosa | Helianthostylis         |           0.5 | Accepted         | Helianthostylis         |
 
```

**Comment by ojalaquellueva** [comment]
Transferring this issue to [TNRSweb](#https://github.com/EnquistLab/TNRSweb)

**Comment by ojalaquellueva** [comment]
@tyeentaylor This issue applies to [TNRSweb](https://github.com/EnquistLab/TNRSweb), not to [TNRSbatch](https://github.com/ojalaquellueva/TNRSbatch) nor to [TNRSapi](https://github.com/ojalaquellueva/TNRSapi). Due to ownership differences, I cannot transfer this issue. However, I will close it here and replicate it at [TNRSweb](https://github.com/EnquistLab/TNRSweb).
