### ISSUE TITLE
Invalid Name_matched_url

### ISSUE THREAD

**Issue by alrichardbollans** [ojalaquellueva/TNRSbatch#8]
Hi,

When I match 'Rosa inermis' there are 10 matches and the powo links are incorrect. E.g. for Rosa inermis Mill. the given link is https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:2970428 but it should be https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:732895-1

**Comment by ojalaquellueva** [comment]
@alrichardbollans Thanks for the issue report. I am currently preparing a new release of the TNRS database. I will investigate the POWO hyperlinks and post an update after I have a diagnosis and fix for the problem.

**Comment by ojalaquellueva** [comment]
@alrichardbollans The issue was indeed a bug in the code that builds the database. The code issue has been fixed and the database rebuilt. To verify, using source WCVP, Rosa inermis Mill. now resolves to https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:732895-1.
